services:
  wikijs:
    image: requarks/wiki:latest
    environment:
      - DB_TYPE=postgres
      - DB_HOST=wikidb
      - DB_PORT=5432
      - DB_NAME=wikijsdb
      - DB_USER=wikijs
      - DB_PASS=lemdpd3t3stdef0lIe
    ports:
      - 80:3000 # Expose wikijs sur 0.0.0.0:80
    networks:
      - net
      - public # ajout du reseau public

  wikidb:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: wikijsdb
      POSTGRES_PASSWORD: lemdpd3t3stdef0lIe
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: unless-stopped
    networks:
      - net
    volumes:
      - /data/webs/wikijs/database:/var/lib/postgresql/data

networks:
  net:
    driver: bridge # reseau interne entre wikijs et wikidb
  public:
    driver: bridge # reseau pour acces externe et interne au wikijs