version: '3.3'

services:

 traefik:
   image: traefik:v3.1.4
   ports:
     - target: 80
       published: 80
       mode: host
     - target: 443
       published: 443
       mode: host
   deploy:
     placement:
       constraints:
         - node.role == manager
     mode: global
     #mode: replicated
     #replicas: 5
     update_config:
       parallelism: 1
       delay: 300s

     labels:
       - traefik.enable=true
       - traefik.docker.network=traefik-public-network
       - traefik.constraint-label=traefik-public
       - traefik.http.middlewares.admin-auth.basicauth.users=ptitgris:$$apr1$$zF32L6gz$$ZO31R97YV4rNMbjGNtZcf/,torenka:$$apr1$$3F0CtQKF$$ZbhCLR3RJB5dL5VNPlLAn/
       - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
       - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
       - "traefik.http.middlewares.modsecurity.plugin.traefik-modsecurity-plugin.BadRequestsThresholdCount=25"
       - "traefik.http.middlewares.modsecurity.plugin.traefik-modsecurity-plugin.BadRequestsThresholdPeriodSecs=600"
       - "traefik.http.middlewares.modsecurity.plugin.traefik-modsecurity-plugin.JailEnabled=false"
       - "traefik.http.middlewares.modsecurity.plugin.traefik-modsecurity-plugin.JailTimeDurationSecs=600"
       - "traefik.http.middlewares.modsecurity.plugin.traefik-modsecurity-plugin.ModsecurityUrl=http://waf:8080"
       - "traefik.http.middlewares.modsecurity.plugin.traefik-modsecurity-plugin.TimeoutMillis=2000"
       - traefik.http.routers.traefik-public-http.rule=Host(`proxy.ptigris200.overthelog.com`)
       - traefik.http.routers.traefik-public-http.entrypoints=http
       - traefik.http.routers.traefik-public-http.middlewares=https-redirect
       - traefik.http.routers.traefik-public-https.rule=Host(`proxy.ptigris200.overthelog.com`)
       - traefik.http.routers.traefik-public-https.entrypoints=https
       - traefik.http.routers.traefik-public-https.tls=true
       - traefik.http.routers.traefik-public-https.tls.certresolver=le
       - traefik.http.routers.traefik-public-https.service=api@internal
       - traefik.http.routers.traefik-public-https.middlewares=admin-auth
       - traefik.http.services.traefik-public.loadbalancer.server.port=8080
       - traefik.tls.options.intermediate.minVersion="VersionTLS12"
       - traefik.tls.options.intermediate.cipherSuites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
       
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock:ro
     - /opt/nas/stacks/traefik/ssl:/etc/certs/
     - /opt/nas/stacks/traefik/cfg:/etc/traefik/dynamic/
     - traefik-public-certificates:/certificates
   command:
     - --providers.docker
     - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
     - --providers.docker.exposedbydefault=false
     - --providers.swarm.endpoint=unix:///var/run/docker.sock
     - --entrypoints.http.address=:80
     - --entrypoints.https.address=:443
     - --serverstransport.insecureskipverify=true
     - --experimental.plugins.traefik-modsecurity-plugin.modulename=github.com/madebymode/traefik-modsecurity-plugin
     - --experimental.plugins.traefik-modsecurity-plugin.version=v1.6.0
     - "--certificatesresolvers.le.acme.email=ptitgris@overthelog.com"
     - --certificatesresolvers.le.acme.storage=/certificates/acme.json
     - --certificatesresolvers.le.acme.tlschallenge=true
     - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=http"
     - --log
     - --api
   networks:
     - traefik-public-network
     - swarmpit-public
     - spinlog

volumes:
 traefik-public-certificates:
networks:
 traefik-public-network:
   external: true

